/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loginOtp`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/expert/online`; params?: Router.UnknownInputParams; } | { pathname: `/expert/recommended`; params?: Router.UnknownInputParams; } | { pathname: `/expert/search`; params?: Router.UnknownInputParams; } | { pathname: `/home/edit`; params?: Router.UnknownInputParams; } | { pathname: `/home/expertProfile`; params?: Router.UnknownInputParams; } | { pathname: `/home/jobSeekerProfile`; params?: Router.UnknownInputParams; } | { pathname: `/home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/home/roleSelection`; params?: Router.UnknownInputParams; } | { pathname: `/expert/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/loginOtp`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/expert/online`; params?: Router.UnknownOutputParams; } | { pathname: `/expert/recommended`; params?: Router.UnknownOutputParams; } | { pathname: `/expert/search`; params?: Router.UnknownOutputParams; } | { pathname: `/home/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/home/expertProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/home/jobSeekerProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/home/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/home/roleSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/expert/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/loginOtp${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/dashboard/dashboard${`?${string}` | `#${string}` | ''}` | `/expert/online${`?${string}` | `#${string}` | ''}` | `/expert/recommended${`?${string}` | `#${string}` | ''}` | `/expert/search${`?${string}` | `#${string}` | ''}` | `/home/edit${`?${string}` | `#${string}` | ''}` | `/home/expertProfile${`?${string}` | `#${string}` | ''}` | `/home/jobSeekerProfile${`?${string}` | `#${string}` | ''}` | `/home/profile${`?${string}` | `#${string}` | ''}` | `/home/roleSelection${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loginOtp`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/expert/online`; params?: Router.UnknownInputParams; } | { pathname: `/expert/recommended`; params?: Router.UnknownInputParams; } | { pathname: `/expert/search`; params?: Router.UnknownInputParams; } | { pathname: `/home/edit`; params?: Router.UnknownInputParams; } | { pathname: `/home/expertProfile`; params?: Router.UnknownInputParams; } | { pathname: `/home/jobSeekerProfile`; params?: Router.UnknownInputParams; } | { pathname: `/home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/home/roleSelection`; params?: Router.UnknownInputParams; } | `/expert/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/expert/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
